project_id = "lgrugpsyewvinlkgmeve"

[functions.create-checkout-session]
verify_jwt = false

[functions.generate-demo-audio]
verify_jwt = false

[functions.send-influencer-term]
verify_jwt = false

[functions.generate-blog-content]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.suggest-blog-title]
verify_jwt = false

[functions.reset-deletion-password]
verify_jwt = false

[functions.send-barber-term]
verify_jwt = false

[functions.appointment-reminders]
verify_jwt = false

[functions.marketing-automations]
verify_jwt = false

[functions.blog-share]
verify_jwt = false

[functions.manage-stripe-keys]
verify_jwt = false